name: TokenMPG
version: '${project.version}'
main: me.gacekmpl2.TokenMPG
api-version: 1.20
authors: [ GacekMPL2 ]

commands:
  token:
    description: Komenda do zarządzania tokenami graczy
    usage: /token